source 'https://rubygems.org'

gem 'mysql2'
gem 'sinatra'
# gem 'thin'
gem 'puma'
gem 'redis'
gem 'faraday'

group :development do
  gem 'sinatra-contrib', require: nil
  gem 'pry'
  gem 'faraday'
  gem 'faraday_middleware'
  gem 'activesupport'
  gem 'diffy'
end
