---
- name: Deploy isucon
  hosts: web
  become: yes
  become_user: root
  roles:
    - app
    - nginx
    - redis

# ---
# - name: Deploy isucon
#   hosts: web
#   become: yes
#   become_user: root
#   roles:
#     - app

# ---
# - name: Deploy isucon
#   hosts: lb
#   become: yes
#   become_user: root
#   roles:
#     - nginx

# ---
# - name: Deploy isucon
#   hosts: redis
#   become: yes
#   become_user: root
#   roles:
#     - redis

# ---
# - name: Deploy isucon
#   hosts: db
#   become: yes
#   become_user: root
#   roles:
#     - mysql
